console.log('🔍 Test del Caricamento del Componente\n');

console.log('📋 Cosa Controllare:');
console.log('');
console.log('1️⃣ RICARICA LA PAGINA:');
console.log('   - Vai su http://localhost:3000');
console.log('   - Naviga al corso "Finanziamento Aziendale"');
console.log('   - Clicca sulla prima lezione');
console.log('   - RICARICA la pagina (F5 o Ctrl+R)');
console.log('');
console.log('2️⃣ CERCA IL DEBUG INFO:');
console.log('   - Dovresti vedere una box GIALLA con "Debug Info:"');
console.log('   - Mostra lo stato del componente');
console.log('');
console.log('3️⃣ POSSIBILI STATI:');
console.log('   ✅ Video Material: ✅ = Video trovato');
console.log('   ❌ Video Material: ❌ = Nessun video');
console.log('   Video Started: ❌ = Non ancora iniziato');
console.log('   Video Ended: ❌ = Non ancora finito');
console.log('');
console.log('4️⃣ SE VEDI IL DEBUG INFO:');
console.log('   - Il componente si sta caricando correttamente');
console.log('   - Controlla i valori mostrati');
console.log('');
console.log('5️⃣ SE NON VEDI NIENTE:');
console.log('   - Controlla la console del browser (F12)');
console.log('   - Cerca errori JavaScript');
console.log('   - Verifica che la pagina si carichi completamente');
console.log('');
console.log('6️⃣ CONSOLE DEL BROWSER:');
console.log('   - Apri F12 → Console');
console.log('   - Dovresti vedere:');
console.log('     🔍 LessonWithQuiz Debug: {...}');
console.log('     🔍 LessonWithQuiz render: {...}');
console.log('');
console.log('🎯 Il debug info ti dirà esattamente cosa sta succedendo!');
